# Generated by Django 5.1.5 on 2025-02-04 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='roll_number',
        ),
        migrations.AlterField(
            model_name='exam',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qustion_exams', to='base.question'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='selected_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_option', to='base.option'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exams', to=settings.AUTH_USER_MODEL),
        ),
    ]
