# Generated by Django 5.1.5 on 2025-02-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_exam_roll_number_alter_exam_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
