# Generated by Django 5.1.5 on 2025-02-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_option_is_checked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='is_checked',
            new_name='release',
        ),
    ]
