# Generated by Django 5.1.5 on 2025-02-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_is_checked_option_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='release',
        ),
        migrations.AddField(
            model_name='exam',
            name='release',
            field=models.BooleanField(default=False),
        ),
    ]
