# Generated by Django 5.1.5 on 2025-02-04 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_option_release_exam_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='release',
        ),
    ]
